CONFIG_ZMK_KEYBOARD_NAME="Athena"

# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Bluetooth power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y


# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Turn OFF Nice View Gem features for testing
# CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE is not set
# CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE_MAX=100
# CONFIG_NICE_VIEW_GEM_ANIMATION is not set
# CONFIG_NICE_VIEW_GEM_ANIMATION_MS=500
