name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        shield:
          - corne_left
          - corne_right

    steps:
      - name: Checkout ZMK Config
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install west and dependencies
        run: |
          pip install west
          west init -l config
          west update
          west zephyr-export
          pip install -r zmk/app/zephyr/scripts/requirements.txt

      - name: Build ZMK for ${{ matrix.shield }}
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=${{ matrix.shield }}
